name: 'Setup reviewdog'
description: '🐶 This action sets up reviewdog'
inputs:
  reviewdog_version:
    description: 'reviewdog version. [latest,nightly,vX.Y.Z]'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/install.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: ${{ inputs.reviewdog_version }}
        REVIEWDOG_TEMPDIR: ${{ runner.temp }}
    - run: |
        echo "::group::📖 reviewdog -version"
        reviewdog -version
        echo "::endgroup::"
      shell: bash

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'terminal'
  color: 'gray-dark'
