name: 'Setup reviewdog'
description: 'ðŸ¶ This action sets up reviewdog'
inputs:
  reviewdog_version:
    description: 'reviewdog version. [latest,vX.Y.Z]'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: winnielabs/reviewdog
        path: reviewdog
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        cache: true
        cache-dependency-path: reviewdog/go.sum
    - run: go build
      working-directory: reviewdog/cmd/reviewdog/
      shell: bash
    - run: echo "$(pwd)/reviewdog/cmd/reviewdog" >> "$GITHUB_PATH"
      shell: bash
    - run: |
        echo "::group::ðŸ“– reviewdog -version"
        reviewdog -version
        echo "::endgroup::"
      shell: bash

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'terminal'
  color: 'gray-dark'
