name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install reviewdog
        uses: ./

      - name: Check reviewdog version
        shell: bash
        run: |
          reviewdog -version
          test "$(reviewdog -version)" = 'master'
