name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: install reviewdog (default)
        uses: ./
      - run: reviewdog -version

      - name: install reviewdog (with reviewdog_version)
        uses: ./
        with:
          reviewdog_version: v0.10.0
      - run: test "$(reviewdog -version)" = '0.10.0'
